### ISSUE TITLE
Z3 error when running example: "Illegal value 45101 for Z3_decl_kind"

### ISSUE THREAD

**Issue by cdstanford** [dragosdmtrsc/vera2#1]
Hello,

We installed Z3 with java bindings on Linux, and we are getting the following error when running: "Illegal value 45101 for Z3_decl_kind".

I am suspecting a Z3 versioning issue. We would like to try compiling with an old version of Z3 -- what version of Z3 did you use for Vera?

Thank you!
Caleb

Full output:
```
$ sudo ./target/vera.sh inputs/test-cases/simple-router/simple_router-ppc.p4
preparing to run vera against inputs/test-cases/simple-router/simple_router-ppc.p4
WARNING: unknown parameter 'model_compress'
Legal parameters are:
  auto_config (bool) (default: true)
  debug_ref_count (bool) (default: false)
  dot_proof_file (string) (default: proof.dot)
  dump_models (bool) (default: false)
  model (bool) (default: true)
  model_validate (bool) (default: false)
  proof (bool) (default: false)
  rlimit (unsigned int) (default: 0)
  smtlib2_compliant (bool) (default: false)
  stats (bool) (default: false)
  timeout (unsigned int) (default: 4294967295)
  trace (bool) (default: false)
  trace_file_name (string) (default: z3.log)
  type_check (bool) (default: true)
  unsat_core (bool) (default: false)
  well_sorted_check (bool) (default: false)

Oct 06, 2021 3:44:12 PM org.change.p4.control.queryimpl.PacketKind$$anonfun$apply$1 apply
INFO: max packet size 272
Exception in thread "main" java.lang.IllegalArgumentException: Illegal value 45101 for Z3_decl_kind
	at com.microsoft.z3.enumerations.Z3_decl_kind.fromInt(Z3_decl_kind.java:273)
	at com.microsoft.z3.FuncDecl.getDeclKind(FuncDecl.java:121)
	at com.microsoft.z3.Expr.isAnd(Expr.java:351)
	at org.change.p4.control.queryimpl.RootMemory.andArgs(RootMemory.scala:138)
	at org.change.p4.control.queryimpl.RootMemory.mkAnd2(RootMemory.scala:152)
	at org.change.p4.control.queryimpl.RootMemory.where(RootMemory.scala:333)
	at org.change.p4.control.queryimpl.P4RootMemory.where(P4RootMemory.scala:347)
	at org.change.p4.control.QueryDrivenSemantics.mkQuery(QueryDrivenSemantics.scala:707)
	at org.change.p4.control.QueryDrivenSemantics.translate(QueryDrivenSemantics.scala:743)
	at org.change.p4.control.QueryDrivenSemantics.translate(QueryDrivenSemantics.scala:15)
	at org.change.p4.control.Semantics$$anonfun$runOnCFG$1$$anonfun$apply$1$$anonfun$4$$anonfun$apply$2.apply(Semantics.scala:127)
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:55)
	at org.change.p4.control.Semantics$$anonfun$runOnCFG$1$$anonfun$apply$1$$anonfun$4.apply(Semantics.scala:147)
	at org.change.p4.control.Semantics$$anonfun$runOnCFG$1$$anonfun$apply$1$$anonfun$4.apply(Semantics.scala:126)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:111)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at org.change.p4.control.Semantics$$anonfun$runOnCFG$1$$anonfun$apply$1.apply(Semantics.scala:126)
	at org.change.p4.control.Semantics$$anonfun$runOnCFG$1$$anonfun$apply$1.apply(Semantics.scala:123)
	at scala.Option.map(Option.scala:145)
	at org.change.p4.control.Semantics$$anonfun$runOnCFG$1.apply(Semantics.scala:123)
	at org.change.p4.control.Semantics$$anonfun$runOnCFG$1.apply(Semantics.scala:108)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:111)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at org.change.p4.control.Semantics.runOnCFG(Semantics.scala:108)
	at org.change.p4.control.Semantics.parse(Semantics.scala:47)
	at org.change.p4.tools.Vera$.main(Vera.scala:122)
	at org.change.p4.tools.Vera.main(Vera.scala)
```

**Comment by cdstanford** [comment]
Hello,

If anyone can see this, can I confirm what platform vera2 will work on, with what exact version of Z3?
@radustoenescu @dragosdmtrsc 

Thank you,
Caleb

**Comment by dragosdmtrsc** [comment]
Hi, Caleb,
Could you please try with version 4.8.4? [1] This should work both for Vera (refers to the SIGCOMM'18 paper) [2] and Vera2 (this repo).
Thanks,
Dragos

[1] - https://github.com/Z3Prover/z3/releases/tag/z3-4.8.4
[2] - https://github.com/dragosdmtrsc/oldvera
